### ISSUE TITLE
about video matting  under the green screen

### ISSUE THREAD

**Issue by zhanghongyong123456** [michaelowenliu/awesome-image-matting#2]
I would like to ask if you study image matting. I want to realize a green screen matting. Which project is better, mainly for hair and translucent images under the green screen，
Looking forward to your reply

**Comment by zhanghongyong123456** [comment]
> @zhanghongyong123456 Hi, I have listed a few great open-sourced matting projects. You could pick up one or two from them. Did you try PaddleSeg? https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.3/contrib/Matting
I saw the matting list you submitted just now, so I would like to ask if you are specialized inmatting, and if there is a good green screen matting project.you can recommend it，I'll try this one you recommended

Thanks again for your collection

**Comment by michaelowenliu** [comment]
> > @zhanghongyong123456 Hi, I have listed a few great open-sourced matting projects. You could pick up one or two from them. Did you try PaddleSeg? https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.3/contrib/Matting
> 
> I saw that his model is Modnet and DIM. Is it just a framework based on these two projects, rather than a retraining ![image](https://user-images.githubusercontent.com/48466610/138069315-9ec5018b-f1f6-481f-b1fc-2e438b692678.png)

Hi, they are pretrained models. Please follow its instruction for prediction using the models.
